services:
  # ---------- Front‑end ----------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"            # host port 3000 → container 80
    env_file:
      - .env                # your React env vars (if any)
    restart: unless-stopped

  # ---------- n8n ----------
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"        # n8n UI & webhook endpoint
    environment:
      # Basic auth – change for production!
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      # (Optional) set a different DB backend, e.g., Postgres:
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=db
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=secret
    volumes:
      - n8n-data:/home/node/.n8n   # persistence

volumes:
  n8n-data:
 