services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - react-app
      - n8n

  certbot:
    image: certbot/certbot:v2.10.0
    container_name: certbot
    volumes:
      - ./certbot/www:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: sh -c "
                      certbot certonly --webroot -w /usr/share/nginx/html \
                      -d ep.clouddevnux.online \
                      -d www.clouddevnux.online \
                      --email devnuxcode@gmail.com \
                      --agree-tos --no-eff-email --non-interactive && \
                      while :; do
                      certbot renew --webroot -w /usr/share/nginx/html && \
                      nginx -s reload || true;
                      sleep 12h;
                      done
                      "

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=167.71.148.184
      - N8N_PORT=5678
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data: