services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .conf/:/etc/nginx/conf.d:ro
      - ./certbot/www:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot:v2.10.0
    container_name: certbot
    volumes:
      - ./certbot/www:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
    command: [
      "certonly",
      "--webroot",
      "-w", "/usr/share/nginx/html",
      "-d", "ep.clouddevnux.online",
      "-d", "www.clouddevnux.online",
      "--email", "devnuxcode@gmail.com",
      "--agree-tos",
      "--no-eff-email"
    ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - n8n
    volumes:
      - .conf:/etc/nginx/conf.d/:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=167.71.148.184
      - N8N_PORT=5678
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data: